
vlog proces_tb.v
vsim proces_tb

add wave -position insertpoint  \
sim:/proces_tb/pro/alu_op \
sim:/proces_tb/pro/alu_op_buff2 \
sim:/proces_tb/pro/alu_op_flush_mux_out \
sim:/proces_tb/pro/alu_out \
sim:/proces_tb/pro/alu_out_buff3 \
sim:/proces_tb/pro/alu_out_buff4 \
sim:/proces_tb/pro/alu_src \
sim:/proces_tb/pro/alu_src_buff2 \
sim:/proces_tb/pro/alu_src_flush_mux_out \
sim:/proces_tb/pro/arth \
sim:/proces_tb/pro/arth_buff2 \
sim:/proces_tb/pro/arth_buff3 \
sim:/proces_tb/pro/branch_buff2 \
sim:/proces_tb/pro/branch_buff3 \
sim:/proces_tb/pro/call \
sim:/proces_tb/pro/call_buff2 \
sim:/proces_tb/pro/call_flush_mux_out \
sim:/proces_tb/pro/clk \
sim:/proces_tb/pro/data_out_buff4 \
sim:/proces_tb/pro/data_out_from_mem \
sim:/proces_tb/pro/data_out_from_mux \
sim:/proces_tb/pro/data_out_from_wb \
sim:/proces_tb/pro/final_freeze_pc \
sim:/proces_tb/pro/final_jump_addr \
sim:/proces_tb/pro/final_jump_addr_after_ldd_jmp \
sim:/proces_tb/pro/final_pc_out_from_buff1 \
sim:/proces_tb/pro/final_pc_segment \
sim:/proces_tb/pro/final_popped_pc \
sim:/proces_tb/pro/flags_out \
sim:/proces_tb/pro/flags_out_from_buff3 \
sim:/proces_tb/pro/flags_out_from_buff4 \
sim:/proces_tb/pro/flags_out_from_mux_rti \
sim:/proces_tb/pro/flush \
sim:/proces_tb/pro/flush_buff2 \
sim:/proces_tb/pro/flush_buff2_from_call \
sim:/proces_tb/pro/flush_buff2_from_ic \
sim:/proces_tb/pro/forwardA \
sim:/proces_tb/pro/forwardB \
sim:/proces_tb/pro/freeze_pc \
sim:/proces_tb/pro/freeze_pc_from_call \
sim:/proces_tb/pro/imm \
sim:/proces_tb/pro/imm_buff2 \
sim:/proces_tb/pro/imm_flush_mux_out \
sim:/proces_tb/pro/imm_indicator \
sim:/proces_tb/pro/imm_mux \
sim:/proces_tb/pro/immediate \
sim:/proces_tb/pro/immediate_buff2 \
sim:/proces_tb/pro/IN_PORT \
sim:/proces_tb/pro/in_port \
sim:/proces_tb/pro/in_port_buff2 \
sim:/proces_tb/pro/in_port_buff3 \
sim:/proces_tb/pro/in_port_buff4 \
sim:/proces_tb/pro/IN_PORT_buffer1 \
sim:/proces_tb/pro/IN_PORT_buffer2 \
sim:/proces_tb/pro/IN_PORT_buffer3 \
sim:/proces_tb/pro/IN_PORT_buffer4 \
sim:/proces_tb/pro/in_port_flush_mux_out \
sim:/proces_tb/pro/inc_dec_sp \
sim:/proces_tb/pro/inc_dec_sp_buff2 \
sim:/proces_tb/pro/inc_dec_sp_buff3 \
sim:/proces_tb/pro/inc_dec_sp_flush_mux_out \
sim:/proces_tb/pro/inc_popped_pc \
sim:/proces_tb/pro/instr_from_mux \
sim:/proces_tb/pro/instr_out_from_buff1 \
sim:/proces_tb/pro/instr_out_from_buff2 \
sim:/proces_tb/pro/instr_out_from_buff3 \
sim:/proces_tb/pro/INTR \
sim:/proces_tb/pro/jdu_out_flags \
sim:/proces_tb/pro/jump_sign \
sim:/proces_tb/pro/jump_type \
sim:/proces_tb/pro/jump_type_buff2 \
sim:/proces_tb/pro/jump_type_buff3 \
sim:/proces_tb/pro/jump_type_flush_mux_out \
sim:/proces_tb/pro/ldd_or_std \
sim:/proces_tb/pro/ldd_or_std_buff2 \
sim:/proces_tb/pro/ldd_or_std_buff3 \
sim:/proces_tb/pro/ldd_or_std_flush_mux_out \
sim:/proces_tb/pro/mem_read \
sim:/proces_tb/pro/mem_read_buff2 \
sim:/proces_tb/pro/mem_read_buff3 \
sim:/proces_tb/pro/mem_read_buff4 \
sim:/proces_tb/pro/mem_read_flush_mux_out \
sim:/proces_tb/pro/mem_to_register \
sim:/proces_tb/pro/mem_to_register_buff2 \
sim:/proces_tb/pro/mem_to_register_buff3 \
sim:/proces_tb/pro/mem_to_register_buff4 \
sim:/proces_tb/pro/mem_to_register_flush_mux_out \
sim:/proces_tb/pro/mem_write \
sim:/proces_tb/pro/mem_write_buff2 \
sim:/proces_tb/pro/mem_write_buff3 \
sim:/proces_tb/pro/mem_write_flush_mux_out \
sim:/proces_tb/pro/mem_write_from_call \
sim:/proces_tb/pro/mem_write_from_ic \
sim:/proces_tb/pro/mem_write_to_mem \
sim:/proces_tb/pro/next_pc_out_from_fetch \
sim:/proces_tb/pro/nop_from_luc \
sim:/proces_tb/pro/nop_from_ret_case_of_intr_after_call \
sim:/proces_tb/pro/nop_signal_from_call \
sim:/proces_tb/pro/nop_signal_from_intr \
sim:/proces_tb/pro/Oh_INTR \
sim:/proces_tb/pro/out_addr \
sim:/proces_tb/pro/OUT_FLAGS_FROM_FLAG_REGISTER \
sim:/proces_tb/pro/out_flags_from_flags_mux \
sim:/proces_tb/pro/out_from_forward_unit_controller \
sim:/proces_tb/pro/out_from_hazard_controller \
sim:/proces_tb/pro/out_from_mux_1_before_alu \
sim:/proces_tb/pro/out_from_mux_2_before_alu \
sim:/proces_tb/pro/OUT_INTR_FROM_DELAYER \
sim:/proces_tb/pro/OUT_INTR_FROM_PRODUCER \
sim:/proces_tb/pro/OUT_PORT \
sim:/proces_tb/pro/pc_h_final \
sim:/proces_tb/pro/pc_h_from_wb \
sim:/proces_tb/pro/pc_l_final \
sim:/proces_tb/pro/pc_l_from_buff4 \
sim:/proces_tb/pro/pc_l_from_wb \
sim:/proces_tb/pro/pc_out_from_buff1 \
sim:/proces_tb/pro/pc_out_from_buff2 \
sim:/proces_tb/pro/pc_out_from_buff3 \
sim:/proces_tb/pro/pc_out_from_pc \
sim:/proces_tb/pro/pc_segment \
sim:/proces_tb/pro/pc_segment_from_call \
sim:/proces_tb/pro/pc_to_stack \
sim:/proces_tb/pro/pc_to_stack_buff2 \
sim:/proces_tb/pro/pc_to_stack_buff3 \
sim:/proces_tb/pro/pc_to_stack_buff4 \
sim:/proces_tb/pro/pc_to_stack_flush_mux_out \
sim:/proces_tb/pro/pc_to_stack_from_call \
sim:/proces_tb/pro/pc_to_stack_from_ic \
sim:/proces_tb/pro/pc_to_stack_mem_in \
sim:/proces_tb/pro/pop_segment_ret \
sim:/proces_tb/pro/pop_segment_rti \
sim:/proces_tb/pro/popped_pc_after_imm_check \
sim:/proces_tb/pro/popped_pc_temp \
sim:/proces_tb/pro/read_addr_1_buff2 \
sim:/proces_tb/pro/read_addr_1_buff3 \
sim:/proces_tb/pro/read_addr_2_buff2 \
sim:/proces_tb/pro/read_addr_2_buff3 \
sim:/proces_tb/pro/read_addr_2_buff4 \
sim:/proces_tb/pro/read_data_1 \
sim:/proces_tb/pro/read_data_1_buff2 \
sim:/proces_tb/pro/read_data_1_mux \
sim:/proces_tb/pro/read_data_2 \
sim:/proces_tb/pro/read_data_2_buff2 \
sim:/proces_tb/pro/read_data_2_buff3 \
sim:/proces_tb/pro/register_write_buff2 \
sim:/proces_tb/pro/register_write_buff3 \
sim:/proces_tb/pro/register_write_buff4 \
sim:/proces_tb/pro/register_write_flush_mux_out \
sim:/proces_tb/pro/register_write_out \
sim:/proces_tb/pro/reset \
sim:/proces_tb/pro/ret \
sim:/proces_tb/pro/ret_buff2 \
sim:/proces_tb/pro/ret_buff3 \
sim:/proces_tb/pro/ret_buff4 \
sim:/proces_tb/pro/ret_flush_mux_out \
sim:/proces_tb/pro/ret_pop \
sim:/proces_tb/pro/rti \
sim:/proces_tb/pro/rti_buff2 \
sim:/proces_tb/pro/rti_buff3 \
sim:/proces_tb/pro/rti_flush_mux_out \
sim:/proces_tb/pro/rti_pop \
sim:/proces_tb/pro/stack_or_data \
sim:/proces_tb/pro/stack_or_data_buff2 \
sim:/proces_tb/pro/stack_or_data_buff3 \
sim:/proces_tb/pro/stack_or_data_flush_mux_out \
sim:/proces_tb/pro/stall \
sim:/proces_tb/pro/stall2 \
sim:/proces_tb/pro/stall_jump \
sim:/proces_tb/pro/take_call_pc \
sim:/proces_tb/pro/take_intr_from_ic \
sim:/proces_tb/pro/take_jmp_pc_from_suj_luc \
sim:/proces_tb/pro/tempRETI_BUFF4 \
sim:/proces_tb/pro/unconditional_jump \
sim:/proces_tb/pro/write_addr \
sim:/proces_tb/pro/write_addr_buff4 \
sim:/proces_tb/pro/write_data \
sim:/proces_tb/pro/write_flags \
sim:/proces_tb/pro/write_flags_out \
sim:/proces_tb/pro/write_pc_ret \
sim:/proces_tb/pro/write_pc_ret_out \
sim:/proces_tb/pro/write_pc_rti \
sim:/proces_tb/pro/write_pc_rti_out \
sim:/proces_tb/pro/write_popped_pc
add wave -position insertpoint  \
sim:/proces_tb/pro/dec/RF/array_reg \
sim:/proces_tb/pro/dec/RF/write_addr \
sim:/proces_tb/pro/dec/RF/write_data
add wave -position insertpoint  \
sim:/proces_tb/pro/fc/call \
sim:/proces_tb/pro/fc/clk \
sim:/proces_tb/pro/fc/flush \
sim:/proces_tb/pro/fc/jump \
sim:/proces_tb/pro/fc/pc_to_stack \
sim:/proces_tb/pro/fc/ready \
sim:/proces_tb/pro/fc/rst \
sim:/proces_tb/pro/fc/state1 \
sim:/proces_tb/pro/fc/state2 \
sim:/proces_tb/pro/fc/state3 \
sim:/proces_tb/pro/fc/state4 \
sim:/proces_tb/pro/fc/state5 \
sim:/proces_tb/pro/fc/state_next \
sim:/proces_tb/pro/fc/state_reg \
sim:/proces_tb/pro/fc/unconditional_jump
add wave -position insertpoint  \
sim:/proces_tb/pro/jdu1/carry_detector \
sim:/proces_tb/pro/jdu1/in_flags \
sim:/proces_tb/pro/jdu1/JC \
sim:/proces_tb/pro/jdu1/jmp_sign \
sim:/proces_tb/pro/jdu1/JN \
sim:/proces_tb/pro/jdu1/jump_type \
sim:/proces_tb/pro/jdu1/JZ \
sim:/proces_tb/pro/jdu1/negative_detector \
sim:/proces_tb/pro/jdu1/out_flags \
sim:/proces_tb/pro/jdu1/reset \
sim:/proces_tb/pro/jdu1/zero_detector
add wave -position insertpoint  \
sim:/proces_tb/pro/exe1/alu_op \
sim:/proces_tb/pro/exe1/alu_out \
sim:/proces_tb/pro/exe1/alu_out_flags \
sim:/proces_tb/pro/exe1/clk \
sim:/proces_tb/pro/exe1/execute_out \
sim:/proces_tb/pro/exe1/flags \
sim:/proces_tb/pro/exe1/flags_out \
sim:/proces_tb/pro/exe1/imm_rs2_mux_result \
sim:/proces_tb/pro/exe1/imm_rs2_sig \
sim:/proces_tb/pro/exe1/immediate \
sim:/proces_tb/pro/exe1/rs1 \
sim:/proces_tb/pro/exe1/rs2 \
sim:/proces_tb/pro/exe1/rst
add wave -position insertpoint  \
sim:/proces_tb/pro/memo1/alu_address \
sim:/proces_tb/pro/memo1/clk \
sim:/proces_tb/pro/memo1/input_data \
sim:/proces_tb/pro/memo1/mem_address \
sim:/proces_tb/pro/memo1/mem_read \
sim:/proces_tb/pro/memo1/mem_write \
sim:/proces_tb/pro/memo1/mem_write_int \
sim:/proces_tb/pro/memo1/Memory \
sim:/proces_tb/pro/memo1/modified_sp \
sim:/proces_tb/pro/memo1/out_data \
sim:/proces_tb/pro/memo1/pc_to_stack_int \
sim:/proces_tb/pro/memo1/ret_pop \
sim:/proces_tb/pro/memo1/rst \
sim:/proces_tb/pro/memo1/rti_pop \
sim:/proces_tb/pro/memo1/sp \
sim:/proces_tb/pro/memo1/sp_address \
sim:/proces_tb/pro/memo1/stack_or_data
add wave -position insertpoint  \
sim:/proces_tb/pro/read_data_1_buff3
add wave -position insertpoint sim:/proces_tb/pro/fetch/pc_cu/*
add wave -position insertpoint sim:/proces_tb/pro/call_cont/*
add wave -position insertpoint  \
sim:/proces_tb/pro/fu/alu_out_IE_MEM \
sim:/proces_tb/pro/fu/alu_out_MEM_WB \
sim:/proces_tb/pro/fu/clk \
sim:/proces_tb/pro/fu/en \
sim:/proces_tb/pro/fu/forwardA \
sim:/proces_tb/pro/fu/forwardB \
sim:/proces_tb/pro/fu/reg_write_MEM \
sim:/proces_tb/pro/fu/reg_write_WB \
sim:/proces_tb/pro/fu/Rsrc1 \
sim:/proces_tb/pro/fu/Rsrc2
add wave -position insertpoint  \
sim:/proces_tb/pro/final_read_2_data_buff2
add wave -position insertpoint  \
sim:/proces_tb/pro/addr_mux_mem/ldd_or_std \
sim:/proces_tb/pro/addr_mux_mem/out_addr \
sim:/proces_tb/pro/addr_mux_mem/read_1_addr \
sim:/proces_tb/pro/addr_mux_mem/read_2_addr